Refactored FormCarter for testing, added phpunit dependency and basic…
software-things/form-carter pull request #8
Opened 2019-10-25 21:19 UTC by banasmat

- Replaced usage of 'echo' with exceptions and return statements in FormCarter class.
- Removed instantiating Swift_Mailer outside of the class. It's now injected through constructor.
- Removed json response wrapper and header functions outside of the class. It shouldn't be responsible for the 'view'.
These changes made testing the class possible.
Added phpunit dependency with basic tests and info how to run them.

2019-10-28 20:58 UTC, emtei requested changes

2019-10-28 20:58 UTC, emtei commented on st-errors.txt
> +2019-10-25 18:20:37: Connection could not be established with host smtp.example.com [php_network_getaddresses: getaddrinfo failed: No such host is known.  #0]
Should we gitignore this file?

2019-10-28 21:00 UTC, IgorPodlawski commented on st-errors.txt
> +2019-10-25 18:20:37: Connection could not be established with host smtp.example.com [php_network_getaddresses: getaddrinfo failed: No such host is known.  #0]
It's already in .gitignore after #4

2019-10-29 17:21 UTC, kamiljedrkiewicz approved these changes
Thanks, great job.

2019-10-29 17:44 UTC, emtei commented on st-errors.txt
> +2019-10-25 18:20:37: Connection could not be established with host smtp.example.com [php_network_getaddresses: getaddrinfo failed: No such host is known.  #0]
So it needs to be removed from this PR

2019-10-29 17:55 UTC, emtei approved these changes

2019-10-29 17:57 UTC, merged

2019-10-29 17:57 UTC, emtei approved these changes